# Generated by Django 5.1 on 2024-08-14 20:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_email_alter_user_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yeast_infection', models.BooleanField(default=False)),
                ('urinary_track_infections', models.BooleanField(default=False)),
                ('bacterial_vaginosis', models.BooleanField(default=False)),
                ('polycystic_ovary_syndrome', models.BooleanField(default=False)),
                ('endometriosis', models.BooleanField(default=False)),
                ('fibroids', models.BooleanField(default=False)),
                ('i_am_not_sure', models.BooleanField(default=False)),
                ('no_health_issue', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Questionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_period_regular', models.BooleanField(default=False)),
                ('days_between_period', models.IntegerField(default=28)),
                ('length_of_period', models.IntegerField(default=5)),
                ('last_period_start', models.DateField()),
                ('take_birth_control', models.BooleanField(default=False)),
                ('health_condition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questionnaires', to='user.healthcondition')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='user.user')),
            ],
        ),
    ]
