# Generated by Django 5.1 on 2024-08-14 22:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_healthcondition_questionnaire'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start', models.DateField()),
                ('cycle_length', models.IntegerField()),
                ('anomalies', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_history', to='user.user')),
            ],
        ),
    ]
