# Generated by Django 5.1 on 2024-08-15 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_periodhistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeriodPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_start_from', models.DateField()),
                ('period_start_to', models.DateField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='period_predictions', to='user.user')),
            ],
        ),
    ]
