# Generated by Django 5.1 on 2024-08-16 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_periodprediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodprediction',
            name='anomalies',
            field=models.TextField(default='no_enomalies'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='periodprediction',
            name='days_between_period',
            field=models.IntegerField(default=28),
        ),
        migrations.AddField(
            model_name='periodprediction',
            name='length_of_period',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
    ]
