# Generated by Django 5.1 on 2024-08-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_periodprediction_anomalies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='periodhistory',
            name='days_between_period',
            field=models.IntegerField(default=28),
        ),
    ]
